# frozen_string_literal: true

# SPDX-FileCopyrightText: Copyright (c) 2019-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT

require 'json'
require 'net/http'
require 'uri'

require_relative 'rsk'

class Rsk::TaskTracker
  GITHUB_API = 'https://api.github.com'

  def initialize(repo, token)
    @repo = repo
    @token = token
  end

  def create(task, http: nil)
    uri = URI.parse("#{GITHUB_API}/repos/#{@repo}/issues")
    request = Net::HTTP::Post.new(uri.path)
    request['Authorization'] = "Bearer #{@token}"
    request['Content-Type'] = 'application/json'
    request['User-Agent'] = '0rsk'
    request.body = {
      title: "Task: #{task[:ptext]}",
      body: [
        "Risk: #{task[:ctext]} \u2192 #{task[:rtext]} \u2192 #{task[:etext]}",
        "Plan: #{task[:ptext]}",
        "Schedule: #{task[:schedule]}",
        '',
        '_(generated by [0rsk](https://www.0rsk.com))_'
      ].join("\n")
    }.to_json
    (http || the_http(uri)).request(request).tap do |response|
      code = Integer(response.code, 10)
      case code
      when 200..299
        return JSON.parse(response.body)['number']
      when 401
        raise(Rsk::Urror, "GitHub API: invalid token for #{@repo}")
      when 403
        raise(Rsk::Urror, "GitHub API: rate limited or forbidden for #{@repo}")
      when 404
        raise(Rsk::Urror, "GitHub API: repository #{@repo} not found")
      when 422
        errs = JSON.parse(response.body)['errors']
        raise(Rsk::Urror, "GitHub API: #{errs&.map { |e| e['message'] }&.join(', ') || 'validation error'}")
      else
        raise(Rsk::Urror, "GitHub API error (#{code}): #{response.message}")
      end
    end
  rescue Net::ReadTimeout, Net::OpenTimeout => e
    raise(Rsk::Urror, "GitHub API timeout: #{e.message}")
  rescue SocketError, Errno::ECONNREFUSED => e
    raise(Rsk::Urror, "GitHub API connection failed: #{e.message}")
  end

  private

  def the_http(uri)
    h = Net::HTTP.new(uri.host, uri.port)
    h.use_ssl = true
    h.open_timeout = 10
    h.read_timeout = 30
    h
  end
end
