# frozen_string_literal: true

# SPDX-FileCopyrightText: Copyright (c) 2019-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT

require_relative 'rsk'
require 'json'
require 'net/http'
require 'uri'

class Rsk::TaskTracker
  def initialize(repo, token)
    @repo = repo
    @token = token
  end

  def create(task)
    uri = URI.parse("https://api.github.com/repos/#{@repo}/issues")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    request = Net::HTTP::Post.new(uri.path)
    request['Authorization'] = "Bearer #{@token}"
    request['Content-Type'] = 'application/json'
    request.body = {
      title: "Task: #{task[:ptext]}",
      body: [
        "Risk: #{task[:ctext]} → #{task[:rtext]} → #{task[:etext]}",
        "Plan: #{task[:ptext]}",
        "Schedule: #{task[:schedule]}",
        '',
        '_(generated by [0rsk](https://www.0rsk.com))_'
      ].join("\n")
    }.to_json
    response = http.request(request)
    raise(Rsk::Urror, "GitHub API error: #{response.code}") unless (200..299).cover?(Integer(response.code, 10))
    JSON.parse(response.body)['number']
  end
end
